added dictionary attack for rarfiles

diff --git a/wbruter b/wbruter
--- a/wbruter
+++ b/wbruter
@@ -16,6 +16,7 @@ echo "            -A [4] [6] ANDROID GUI      - Brute force attack android devic
 echo "            -h         HELP             - Print this help"
 echo "            -G         GPG              - Dictionary attack for encrypted gpg files"
 echo "            -g         GMAIL            - Brute force attack an gmail account"
+echo "            -r         RAR              - Dictionary attack for rar files"
 echo "            -z         ZIP              - Dictionary and Brute Force attack an zip file"
 echo ""
 }
@@ -381,7 +382,40 @@ done
 }
 
 
-while getopts ":abghGA" getopt; do
+rar() {
+wordlist="wordlist"
+read -p "RAR Filename: (/path/to/file.rar): " rartarget
+
+if [ ! -f $wordlist ]; then
+   printf "Can't find $wordlist, aborted\n"
+      exit
+      fi
+
+      if [[ ! -a $rartarget ]]; then
+      printf "Sorry, can't $rartarget a such file, aborted\n"
+      exit
+      fi
+
+      printf "\n%51s" | tr ' ' '='
+      printf "\nBruteforce attack will be started within 2 seconds..\nPlease use (CTRL+C) to abort the attack at anytime..\n"
+      printf "%51s\n" | tr ' ' '='
+      sleep 2
+
+      while read line; do
+        echo "$line" | unrar p $rartarget &> /dev/null
+        if [[ $? = "0" ]]; then
+        printf "%51s" | tr ' ' '='
+         printf "\nPassword has been found: \e[1;32m$line\e[0m"
+         printf "\n%51s\n\n" | tr ' ' '='
+
+         else
+           printf "Wrong password: \e[1;31m$line\e[0m\n"
+           fi
+           done < wordlist
+}
+
+
+while getopts ":abghGAr" getopt; do
  case $getopt in
    a) androiddebug;adbexist;android_pin_unlock ;;
    A)
@@ -395,6 +429,7 @@ esac ;;
    h) help ;;
    G) gpgd ;;
    g) requirements_gmail; gmail_attack ;;
+   r) rar ;;
    esac
 done
 
